- name: Ensure directories
  file:
    path: "/etc/ldap"
    state: directory

- name: Template out files
  template:
    src: "{{ role_path }}/files/ldap/{{ item }}"
    dest: '/etc/{{ item }}'
  loop:
    - "ldap.conf"
    - "ldap.secret"
    - "/ldap/ldap.conf"
    - "/pam.d/common-session"

- name: Set permission on ldap_secret
  file:
    mode: 0600
    path: /etc/ldap.secret

- name: Ensure permission on common-session
  file:
    mode: 0644
    path: /etc/pam.d/common-session

- name: Run auth-client-config
  shell: "auth-client-config -t nss -p lac_ldap"

- name: Run pam-auth-update
  shell: "pam-auth-update --enable mkhomedir"
  notify:
    - nscd-restart