- name: Ensure directories
  file:
    path: "/etc/ldap"
    state: directory

- name: Template out files
  template:
    src: "{{ role_path }}/files/ldap/{{ item }}"
    dest: '/etc/{{ item }}'
  loop:
    - "ldap.conf"
    - "ldap.secret"
    - "/ldap/ldap.conf"
    - "/pam.d/common-session"
  notify:
      - auth-client-config
      - pam-auth-update
      - nscd-restart

- name: Set permission on ldap_secret
  file:
    mode: 0600
    path: /etc/ldap.secret

- name: Ensure permission on common-session
  file:
    mode: 0644
    path: /etc/pam.d/common-session