---

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
      - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"

- name: Install software via package manager
  include_tasks: software_install.yml

- name: Apply user auth
  include_tasks: user_auth.yml

<<<<<<< HEAD
- name: Apply LDAP config
  include_tasks: ldap.yml
=======
- name: Ensure shared mounts
  include_tasks: mounts.yml
>>>>>>> 7b571b816b57e013c37c738f9b410f4df77569b7
