- name: Ensure directories
  file:
    path: "/share"
    state: directory

- name: Add global mount point for home to fstab
  mount:
    path: /share
    src: 10.50.0.2:/share
    fstype: nfs
    opts: v4.1,_netdev,rw,timeo=600,hard,intr,relatime,async
    state: mounted

- name: Symlink share dirs
  file:
    src: "/share/{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - "projects"
    - "software"

# - name: Symlink home dir
#   file:
#     src: "/share/people"
#     dest: /home
#     owner: root
#     group: root
#     state: link