- name: Ensure directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /software
    - /projects

- name: Add mount points for home to fstab
  mount:
    path: /home
    src: 10.50.0.2:/users
    fstype: nfs
    opts: v4.1,_netdev,rw,timeo=600,hard,intr,relatime,async,rsize=65536,wsize=65536
    state: mounted

- name: Add mount points for tools to fstab
  mount:
    path: /software
    src: 10.50.0.2:/software
    fstype: nfs
    opts: v4.1,_netdev,rw,timeo=600,hard,intr,relatime,async,rsize=65536,wsize=65536
    state: mounted

- name: Add mount points for projects to fstab
  mount:
    path: /projects
    src: 10.50.0.2:/projects
    fstype: nfs
    opts: v4.1,_netdev,rw,timeo=600,hard,intr,relatime,async,rsize=65536,wsize=65536
    state: mounted