- name: Ensure directories
  file:
    path: "/var/local/keys-sync/.ssh"
    state: directory

- name: Template out files
  template:
    src: "{{ role_path }}/files/user_creation/{{ item }}"
    dest: '{{ item }}'
  loop:
    - "/etc/ssh/sshd_config"
    - "/etc/sudoers"
    - "/root/authkeyscommand.sh"
  notify:
    - ssh-restart

- name: Template out keys-sync
  lineinfile:
    create: yes
    state: present
    mode: 0600
    owner: keys-sync
    group: keys-sync
    path: /var/local/keys-sync/.ssh/authorized_keys
    line: "{{ keys_sync_ssh_public_key }}"

- name: Ensure group "keys-sync" exists
  group:
    name: keys-sync
    state: present
    gid: 9000

- name: Ensure user "keys-sync" exists
  user:
    name: keys-sync
    groups: keys-sync
    home: "/var/local/keys-sync"
    shell: /bin/sh
    uid: 9000